- Makefile
- bin/main.go
> Add cli options to print version

- Makefile
> Add arm64 ios android build in makefile

- bin/main.go
> Add cli argument for tuna service name and tuna sub topics

- .gitignore
- tunnel.go
> Allow tsconfig to be nil

- go.mod
- go.sum
> Upgrade tuna and tuna-session version

- .gitignore
- Makefile
> Add makefile command for ios/android

- Makefile
> Add window 32bit build in Makefile

- tunnel.go
> Listen to local only when multiclient is connected

- README.md
- bin/main.go
- config.go
- go.mod
- tunnel.go
* Will listen to both tuna and relay sessions for tuna mode
* Add accept address options
* Add tunnel config and change create tunnel API to use config
* Add cli flag to specify seed node
* Allow empty from address (assume listening at nkn addr)
> API and config changes

- Makefile
> Add nkn-sdk-go to gomobile build target

- go.mod
- go.sum
> Upgrade sdk version to greatly reduce RAM usage

- tunnel.go
> Add tunnel Addr() method

- bin/main.go
> Add cli option to change download geo db behavior

- Makefile
> Fix bin directory ignore goarm

- tunnel.go
> Add API to get internal multiclient and tuna session client

- bin/main.go
- config.go
- go.mod
- go.sum
- tunnel.go
> Add dial timeout

- go.mod
- go.sum
> upgrade nkn sdk and tuna and tuna session version

- go.mod
- go.sum
> upgrade nkn sdk, tuna and tuna session version

- bin/main.go
- go.mod
- go.sum
> Add cli argument for nanopay txn fee

- go.mod
- go.sum
> Upgrade nkn-tuna-session version

- go.mod
- go.sum
> Upgrade nkn-tuna-session version to 895d724

- go.mod
- go.sum
> Upgrade nkn-tuna-session version to 56aeb83
